import type {
  IntegrationAction,
  IntegrationTrigger,
} from "@/lib/integrations-catalog"

function titleFromToolSlug(id: string) {
  return id
    .replace(/^GOOGLE(?:CALENDAR|DRIVE|SHEETS|DOCS)_/, "")
    .replace(/_/g, " ")
    .toLowerCase()
    .replace(/\b\w/g, (char) => char.toUpperCase())
}

function composioAction(
  id: string,
  inputFields: string[] = []
): IntegrationAction {
  return {
    id,
    name: titleFromToolSlug(id),
    description: `Run ${id} with the connected app account.`,
    inputFields,
  }
}

function composioTrigger(
  id: string,
  name: string,
  configFields: string[] = []
): IntegrationTrigger {
  const configText = configFields.length
    ? ` Supports config: ${configFields.join(", ")}.`
    : ""
  return {
    id,
    name,
    description: `Starts from ${id}.${configText}`,
  }
}

export const GOOGLE_CALENDAR_TRIGGERS: IntegrationTrigger[] = [
  composioTrigger(
    "GOOGLECALENDAR_ATTENDEE_RESPONSE_CHANGED_TRIGGER",
    "Attendee Response Changed",
    ["calendarId", "interval", "showDeleted"]
  ),
  composioTrigger(
    "GOOGLECALENDAR_EVENT_CANCELED_DELETED_TRIGGER",
    "Event Canceled or Deleted",
    ["calendarId", "interval"]
  ),
  composioTrigger(
    "GOOGLECALENDAR_EVENT_STARTING_SOON_TRIGGER",
    "Event Starting Soon",
    [
      "calendarId",
      "countdownWindowMinutes",
      "includeAllDay",
      "interval",
      "minutesBeforeStart",
    ]
  ),
  composioTrigger(
    "GOOGLECALENDAR_GOOGLE_CALENDAR_EVENT_CHANGE_TRIGGER",
    "Calendar Event Changes",
    ["calendar_id", "ttl"]
  ),
  composioTrigger(
    "GOOGLECALENDAR_GOOGLE_CALENDAR_EVENT_CREATED_TRIGGER",
    "Event Created",
    ["calendarId", "interval", "showDeleted"]
  ),
  composioTrigger(
    "GOOGLECALENDAR_GOOGLE_CALENDAR_EVENT_SYNC_TRIGGER",
    "Calendar Event Sync",
    ["calendarId", "interval", "showDeleted"]
  ),
  composioTrigger(
    "GOOGLECALENDAR_GOOGLE_CALENDAR_EVENT_UPDATED_TRIGGER",
    "Event Updated",
    ["calendarId", "interval", "showDeleted", "tracked_fields"]
  ),
]

export const GOOGLE_CALENDAR_ACTIONS: IntegrationAction[] = [
  composioAction("GOOGLECALENDAR_ACL_DELETE", ["rule_id", "calendar_id"]),
  composioAction("GOOGLECALENDAR_ACL_GET", ["rule_id", "calendar_id"]),
  composioAction("GOOGLECALENDAR_ACL_INSERT", [
    "role",
    "scope",
    "calendar_id",
    "send_notifications",
  ]),
  composioAction("GOOGLECALENDAR_ACL_LIST", [
    "pageToken",
    "syncToken",
    "calendarId",
    "maxResults",
    "showDeleted",
  ]),
  composioAction("GOOGLECALENDAR_ACL_PATCH", [
    "role",
    "scope",
    "rule_id",
    "calendar_id",
    "send_notifications",
  ]),
  composioAction("GOOGLECALENDAR_ACL_UPDATE", [
    "role",
    "rule_id",
    "calendar_id",
    "send_notifications",
  ]),
  composioAction("GOOGLECALENDAR_ACL_WATCH", [
    "id",
    "type",
    "token",
    "params",
    "address",
    "calendarId",
  ]),
  composioAction("GOOGLECALENDAR_BATCH_EVENTS", ["fail_fast", "operations"]),
  composioAction("GOOGLECALENDAR_CALENDAR_LIST_DELETE", ["calendar_id"]),
  composioAction("GOOGLECALENDAR_CALENDAR_LIST_GET", ["calendarId"]),
  composioAction("GOOGLECALENDAR_CALENDAR_LIST_INSERT", [
    "id",
    "hidden",
    "colorId",
    "selected",
    "backgroundColor",
    "foregroundColor",
    "summaryOverride",
    "color_rgb_format",
    "defaultReminders",
    "notificationSettings",
  ]),
  composioAction("GOOGLECALENDAR_CALENDAR_LIST_PATCH", [
    "hidden",
    "colorId",
    "selected",
    "calendar_id",
    "colorRgbFormat",
    "backgroundColor",
    "foregroundColor",
    "summaryOverride",
    "defaultReminders",
    "notificationSettings",
  ]),
  composioAction("GOOGLECALENDAR_CALENDAR_LIST_UPDATE", [
    "hidden",
    "colorId",
    "selected",
    "calendar_id",
    "colorRgbFormat",
    "backgroundColor",
    "foregroundColor",
    "summaryOverride",
    "defaultReminders",
    "notificationSettings",
  ]),
  composioAction("GOOGLECALENDAR_CALENDAR_LIST_WATCH", [
    "id",
    "type",
    "token",
    "params",
    "address",
    "expiration",
  ]),
  composioAction("GOOGLECALENDAR_CALENDARS_DELETE", ["calendar_id"]),
  composioAction("GOOGLECALENDAR_CALENDARS_UPDATE", [
    "summary",
    "location",
    "timeZone",
    "calendarId",
    "description",
  ]),
  composioAction("GOOGLECALENDAR_CHANNELS_STOP", ["id", "token", "resourceId"]),
  composioAction("GOOGLECALENDAR_CLEAR_CALENDAR", ["calendar_id"]),
  composioAction("GOOGLECALENDAR_COLORS_GET", []),
  composioAction("GOOGLECALENDAR_CREATE_CALENDAR", [
    "summary",
    "location",
    "timezone",
    "description",
  ]),
  composioAction("GOOGLECALENDAR_CREATE_EVENT", [
    "summary",
    "location",
    "timezone",
    "attendees",
    "eventType",
    "recurrence",
    "visibility",
    "calendar_id",
    "description",
    "end_datetime",
  ]),
  composioAction("GOOGLECALENDAR_DELETE_EVENT", [
    "event_id",
    "calendar_id",
    "send_updates",
    "send_notifications",
  ]),
  composioAction("GOOGLECALENDAR_DUPLICATE_CALENDAR", ["summary"]),
  composioAction("GOOGLECALENDAR_EVENTS_GET", [
    "event_id",
    "time_zone",
    "calendar_id",
    "max_attendees",
  ]),
  composioAction("GOOGLECALENDAR_EVENTS_IMPORT", [
    "end",
    "start",
    "source",
    "status",
    "colorId",
    "iCalUID",
    "summary",
    "location",
    "sequence",
    "attendees",
  ]),
  composioAction("GOOGLECALENDAR_EVENTS_INSTANCES", [
    "eventId",
    "timeMax",
    "timeMin",
    "timeZone",
    "pageToken",
    "calendarId",
    "maxResults",
    "showDeleted",
    "maxAttendees",
    "originalStart",
  ]),
  composioAction("GOOGLECALENDAR_EVENTS_LIST", [
    "q",
    "iCalUID",
    "orderBy",
    "timeMax",
    "timeMin",
    "timeZone",
    "pageToken",
    "syncToken",
    "calendarId",
    "eventTypes",
  ]),
  composioAction("GOOGLECALENDAR_EVENTS_LIST_ALL_CALENDARS", [
    "q",
    "time_max",
    "time_min",
    "event_types",
    "calendar_ids",
    "show_deleted",
    "single_events",
    "response_detail",
    "max_results_per_calendar",
  ]),
  composioAction("GOOGLECALENDAR_EVENTS_MOVE", [
    "event_id",
    "calendar_id",
    "destination",
    "send_updates",
  ]),
  composioAction("GOOGLECALENDAR_EVENTS_WATCH", [
    "id",
    "type",
    "token",
    "params",
    "address",
    "payload",
    "calendarId",
  ]),
  composioAction("GOOGLECALENDAR_FIND_EVENT", [
    "query",
    "order_by",
    "time_max",
    "time_min",
    "page_token",
    "calendar_id",
    "event_types",
    "max_results",
    "updated_min",
    "show_deleted",
  ]),
  composioAction("GOOGLECALENDAR_FIND_FREE_SLOTS", [
    "items",
    "time_max",
    "time_min",
    "timezone",
    "group_expansion_max",
    "calendar_expansion_max",
  ]),
  composioAction("GOOGLECALENDAR_FREE_BUSY_QUERY", [
    "items",
    "timeMax",
    "timeMin",
    "timeZone",
    "groupExpansionMax",
    "calendarExpansionMax",
  ]),
  composioAction("GOOGLECALENDAR_GET_CALENDAR", ["calendar_id"]),
  composioAction("GOOGLECALENDAR_GET_CALENDAR_PROFILE", []),
  composioAction("GOOGLECALENDAR_GET_CURRENT_DATE_TIME", ["timezone"]),
  composioAction("GOOGLECALENDAR_LIST_BUILDINGS", [
    "customer",
    "pageToken",
    "maxResults",
  ]),
  composioAction("GOOGLECALENDAR_LIST_CALENDAR_RESOURCES", [
    "query",
    "orderBy",
    "customer",
    "pageToken",
    "maxResults",
  ]),
  composioAction("GOOGLECALENDAR_LIST_CALENDARS", [
    "page_token",
    "sync_token",
    "max_results",
    "show_hidden",
    "show_deleted",
    "min_access_role",
  ]),
  composioAction("GOOGLECALENDAR_LIST_SETTINGS", ["pageToken", "maxResults"]),
  composioAction("GOOGLECALENDAR_PATCH_CALENDAR", [
    "summary",
    "location",
    "timezone",
    "calendar_id",
    "description",
  ]),
  composioAction("GOOGLECALENDAR_PATCH_EVENT", [
    "source",
    "status",
    "summary",
    "color_id",
    "end_time",
    "event_id",
    "location",
    "sequence",
    "timezone",
    "attendees",
  ]),
  composioAction("GOOGLECALENDAR_QUICK_ADD", [
    "text",
    "calendar_id",
    "send_updates",
  ]),
  composioAction("GOOGLECALENDAR_REMOVE_ATTENDEE", [
    "event_id",
    "calendar_id",
    "attendee_email",
  ]),
  composioAction("GOOGLECALENDAR_SETTINGS_GET", ["setting"]),
  composioAction("GOOGLECALENDAR_SETTINGS_LIST", [
    "pageToken",
    "syncToken",
    "maxResults",
  ]),
  composioAction("GOOGLECALENDAR_SETTINGS_WATCH", [
    "id",
    "type",
    "token",
    "params",
    "address",
    "expiration",
  ]),
  composioAction("GOOGLECALENDAR_SYNC_EVENTS", [
    "pageToken",
    "sync_token",
    "calendar_id",
    "event_types",
    "max_results",
    "single_events",
  ]),
  composioAction("GOOGLECALENDAR_UPDATE_EVENT", [
    "summary",
    "event_id",
    "location",
    "timezone",
    "attendees",
    "eventType",
    "recurrence",
    "visibility",
    "calendar_id",
    "description",
  ]),
]

export const GOOGLE_DRIVE_TRIGGERS: IntegrationTrigger[] = [
  composioTrigger(
    "GOOGLEDRIVE_COMMENT_ADDED_TRIGGER",
    "Comment Added (Docs/Sheets/Slides)",
    ["file_id", "interval", "max_files"]
  ),
  composioTrigger("GOOGLEDRIVE_FILE_CREATED_TRIGGER", "File Created", [
    "folder_id",
    "interval",
    "max_results",
    "query",
  ]),
  composioTrigger(
    "GOOGLEDRIVE_FILE_DELETED_OR_TRASHED_TRIGGER",
    "File Deleted or Trashed",
    [
      "drive_id",
      "include_corpus_removals",
      "include_items_from_all_drives",
      "interval",
      "page_size",
      "restrict_to_my_drive",
      "spaces",
    ]
  ),
  composioTrigger(
    "GOOGLEDRIVE_FILE_SHARED_PERMISSIONS_ADDED",
    "File Shared (Permissions Added)",
    ["drive_id", "file_id", "interval", "page_size", "supports_all_drives"]
  ),
  composioTrigger("GOOGLEDRIVE_FILE_UPDATED_TRIGGER", "File Updated", [
    "content_only",
    "drive_id",
    "include_items_from_all_drives",
    "interval",
    "page_size",
  ]),
  composioTrigger("GOOGLEDRIVE_GOOGLE_DRIVE_CHANGES", "Google Drive Changes", [
    "drive_id",
    "include_items_from_all_drives",
    "interval",
    "restrict_to_my_drive",
    "spaces",
  ]),
  composioTrigger(
    "GOOGLEDRIVE_NEW_FILE_MATCHING_QUERY_TRIGGER",
    "New File Matching Query",
    [
      "corpora",
      "driveId",
      "includeItemsFromAllDrives",
      "interval",
      "max_results",
      "query",
      "spaces",
      "supportsAllDrives",
    ]
  ),
]

export const GOOGLE_DRIVE_ACTIONS: IntegrationAction[] = [
  composioAction("GOOGLEDRIVE_ADD_FILE_SHARING_PREFERENCE", [
    "role",
    "type",
    "domain",
    "file_id",
    "email_address",
    "transfer_ownership",
  ]),
  composioAction("GOOGLEDRIVE_ADD_PARENT", [
    "id",
    "fileId",
    "supportsAllDrives",
    "supportsTeamDrives",
    "enforceSingleParent",
  ]),
  composioAction("GOOGLEDRIVE_ADD_PROPERTY", [
    "alt",
    "key",
    "xgafv",
    "fields",
    "fileId",
    "callback",
    "quotaUser",
    "uploadType",
    "visibility",
    "oauth_token",
  ]),
  composioAction("GOOGLEDRIVE_COPY_FILE", ["file_id", "new_title"]),
  composioAction("GOOGLEDRIVE_COPY_FILE_ADVANCED", [
    "alt",
    "key",
    "name",
    "xgafv",
    "fields",
    "fileId",
    "parents",
    "starred",
    "trashed",
    "callback",
  ]),
  composioAction("GOOGLEDRIVE_CREATE_COMMENT", [
    "anchor",
    "content",
    "file_id",
    "quoted_file_content_value",
    "quoted_file_content_mime_type",
  ]),
  composioAction("GOOGLEDRIVE_CREATE_DRIVE", [
    "name",
    "hidden",
    "themeId",
    "colorRgb",
    "requestId",
    "backgroundImageFile",
  ]),
  composioAction("GOOGLEDRIVE_CREATE_FILE", [
    "name",
    "fields",
    "parents",
    "starred",
    "mimeType",
    "description",
    "file_to_upload",
  ]),
  composioAction("GOOGLEDRIVE_CREATE_FILE_FROM_TEXT", [
    "file_name",
    "mime_type",
    "parent_id",
    "text_content",
  ]),
  composioAction("GOOGLEDRIVE_CREATE_FOLDER", ["name", "parent_id"]),
  composioAction("GOOGLEDRIVE_CREATE_PERMISSION", [
    "role",
    "type",
    "domain",
    "file_id",
    "email_address",
    "email_message",
    "expiration_time",
    "transfer_ownership",
    "supports_all_drives",
    "allow_file_discovery",
  ]),
  composioAction("GOOGLEDRIVE_CREATE_PERMISSIONS_BATCH", ["permissions"]),
  composioAction("GOOGLEDRIVE_CREATE_REPLY", [
    "action",
    "fields",
    "content",
    "file_id",
    "comment_id",
  ]),
  composioAction("GOOGLEDRIVE_CREATE_SHORTCUT_TO_FILE", [
    "name",
    "target_id",
    "includeLabels",
    "supportsAllDrives",
    "keepRevisionForever",
    "ignoreDefaultVisibility",
    "includePermissionsForView",
  ]),
  composioAction("GOOGLEDRIVE_CREATE_TEAM_DRIVE", [
    "name",
    "themeId",
    "colorRgb",
    "requestId",
    "backgroundImageFile",
  ]),
  composioAction("GOOGLEDRIVE_DELETE_CHILD", [
    "alt",
    "key",
    "xgafv",
    "fields",
    "childId",
    "callback",
    "folderId",
    "quotaUser",
    "uploadType",
    "oauth_token",
  ]),
  composioAction("GOOGLEDRIVE_DELETE_COMMENT", ["file_id", "comment_id"]),
  composioAction("GOOGLEDRIVE_DELETE_DRIVE", [
    "driveId",
    "allowItemDeletion",
    "useDomainAdminAccess",
  ]),
  composioAction("GOOGLEDRIVE_DELETE_FILE", [
    "fileId",
    "supportsAllDrives",
    "enforceSingleParent",
  ]),
  composioAction("GOOGLEDRIVE_DELETE_PARENT", [
    "alt",
    "key",
    "xgafv",
    "fields",
    "fileId",
    "callback",
    "parentId",
    "quotaUser",
    "uploadType",
    "oauth_token",
  ]),
  composioAction("GOOGLEDRIVE_DELETE_PERMISSION", [
    "file_id",
    "permission_id",
    "supportsAllDrives",
    "useDomainAdminAccess",
  ]),
  composioAction("GOOGLEDRIVE_DELETE_PROPERTY", [
    "alt",
    "key",
    "xgafv",
    "fields",
    "fileId",
    "callback",
    "quotaUser",
    "uploadType",
    "visibility",
    "oauth_token",
  ]),
  composioAction("GOOGLEDRIVE_DELETE_REPLY", [
    "file_id",
    "reply_id",
    "comment_id",
  ]),
  composioAction("GOOGLEDRIVE_DELETE_REVISION", ["file_id", "revision_id"]),
  composioAction("GOOGLEDRIVE_DELETE_TEAM_DRIVE", ["teamDriveId"]),
  composioAction("GOOGLEDRIVE_DOWNLOAD_FILE", ["fileId", "mime_type"]),
  composioAction("GOOGLEDRIVE_DOWNLOAD_FILE2", ["file_id"]),
  composioAction("GOOGLEDRIVE_DOWNLOAD_FILE_OPERATION", [
    "file_id",
    "mime_type",
    "revision_id",
  ]),
  composioAction("GOOGLEDRIVE_EDIT_FILE", ["content", "file_id", "mime_type"]),
  composioAction("GOOGLEDRIVE_EMPTY_TRASH", ["driveId", "enforceSingleParent"]),
  composioAction("GOOGLEDRIVE_EXPORT_GOOGLE_WORKSPACE_FILE", [
    "fileId",
    "mimeType",
  ]),
  composioAction("GOOGLEDRIVE_FIND_FILE", [
    "q",
    "fields",
    "spaces",
    "corpora",
    "driveId",
    "orderBy",
    "pageSize",
    "folder_id",
    "pageToken",
    "include_labels",
  ]),
  composioAction("GOOGLEDRIVE_FIND_FOLDER", [
    "starred",
    "name_exact",
    "name_contains",
    "modified_after",
    "parent_folder_id",
    "name_not_contains",
    "full_text_contains",
    "full_text_not_contains",
  ]),
  composioAction("GOOGLEDRIVE_GENERATE_IDS", ["type", "count", "space"]),
  composioAction("GOOGLEDRIVE_GET_ABOUT", ["fields"]),
  composioAction("GOOGLEDRIVE_GET_APP", ["appId"]),
  composioAction("GOOGLEDRIVE_GET_CHANGE", [
    "alt",
    "key",
    "xgafv",
    "fields",
    "driveId",
    "callback",
    "changeId",
    "quotaUser",
    "uploadType",
    "oauth_token",
  ]),
  composioAction("GOOGLEDRIVE_GET_CHANGES_START_PAGE_TOKEN", [
    "driveId",
    "teamDriveId",
    "supportsAllDrives",
    "supportsTeamDrives",
  ]),
  composioAction("GOOGLEDRIVE_GET_CHILD", [
    "alt",
    "key",
    "xgafv",
    "fields",
    "childId",
    "callback",
    "folderId",
    "quotaUser",
    "uploadType",
    "oauth_token",
  ]),
  composioAction("GOOGLEDRIVE_GET_COMMENT", [
    "fileId",
    "commentId",
    "includeDeleted",
  ]),
  composioAction("GOOGLEDRIVE_GET_DRIVE", [
    "drive_id",
    "use_domain_admin_access",
  ]),
  composioAction("GOOGLEDRIVE_GET_FILE_METADATA", [
    "fields",
    "fileId",
    "includeLabels",
    "supportsAllDrives",
    "includePermissionsForView",
  ]),
  composioAction("GOOGLEDRIVE_GET_FILE_PROPERTY", [
    "fileId",
    "visibility",
    "propertyKey",
  ]),
  composioAction("GOOGLEDRIVE_GET_FILE_V2", [
    "alt",
    "key",
    "xgafv",
    "fields",
    "fileId",
    "callback",
    "quotaUser",
    "projection",
    "revisionId",
    "uploadType",
  ]),
  composioAction("GOOGLEDRIVE_GET_PARENT", [
    "alt",
    "key",
    "xgafv",
    "fields",
    "fileId",
    "callback",
    "parentId",
    "quotaUser",
    "uploadType",
    "oauth_token",
  ]),
  composioAction("GOOGLEDRIVE_GET_PERMISSION", [
    "fields",
    "file_id",
    "permission_id",
    "supports_all_drives",
    "use_domain_admin_access",
  ]),
  composioAction("GOOGLEDRIVE_GET_PERMISSION_ID_FOR_EMAIL", [
    "alt",
    "key",
    "email",
    "xgafv",
    "fields",
    "callback",
    "quotaUser",
    "uploadType",
    "oauth_token",
    "prettyPrint",
  ]),
  composioAction("GOOGLEDRIVE_GET_REPLY", [
    "fileId",
    "replyId",
    "commentId",
    "includeDeleted",
  ]),
  composioAction("GOOGLEDRIVE_GET_REVISION", [
    "file_id",
    "revision_id",
    "acknowledge_abuse",
  ]),
  composioAction("GOOGLEDRIVE_GET_TEAM_DRIVE", [
    "teamDriveId",
    "useDomainAdminAccess",
  ]),
  composioAction("GOOGLEDRIVE_GOOGLE_DRIVE_DELETE_FOLDER_OR_FILE_ACTION", [
    "fileId",
    "supportsAllDrives",
  ]),
  composioAction("GOOGLEDRIVE_HIDE_DRIVE", ["drive_id"]),
  composioAction("GOOGLEDRIVE_INSERT_CHILD", [
    "id",
    "alt",
    "key",
    "xgafv",
    "fields",
    "callback",
    "folderId",
    "quotaUser",
    "uploadType",
    "oauth_token",
  ]),
  composioAction("GOOGLEDRIVE_LIST_ACCESS_PROPOSALS", [
    "fileId",
    "pageSize",
    "pageToken",
  ]),
  composioAction("GOOGLEDRIVE_LIST_APPROVALS", [
    "fileId",
    "pageSize",
    "pageToken",
  ]),
  composioAction("GOOGLEDRIVE_LIST_CHANGES", [
    "spaces",
    "driveId",
    "pageSize",
    "pageToken",
    "includeLabels",
    "includeRemoved",
    "restrictToMyDrive",
    "supportsAllDrives",
    "includeCorpusRemovals",
    "includeItemsFromAllDrives",
  ]),
  composioAction("GOOGLEDRIVE_LIST_CHILDREN_V2", [
    "q",
    "alt",
    "key",
    "xgafv",
    "fields",
    "orderBy",
    "callback",
    "folderId",
    "pageToken",
    "quotaUser",
  ]),
  composioAction("GOOGLEDRIVE_LIST_COMMENTS", [
    "fields",
    "fileId",
    "pageSize",
    "pageToken",
    "includeDeleted",
    "startModifiedTime",
  ]),
  composioAction("GOOGLEDRIVE_LIST_FILE_LABELS", [
    "file_id",
    "page_token",
    "max_results",
  ]),
  composioAction("GOOGLEDRIVE_LIST_FILE_PROPERTIES", [
    "alt",
    "key",
    "xgafv",
    "fields",
    "fileId",
    "callback",
    "quotaUser",
    "uploadType",
    "oauth_token",
    "prettyPrint",
  ]),
  composioAction("GOOGLEDRIVE_LIST_FILES", [
    "q",
    "fields",
    "spaces",
    "corpora",
    "driveId",
    "orderBy",
    "folderId",
    "pageSize",
    "pageToken",
    "includeLabels",
  ]),
  composioAction("GOOGLEDRIVE_LIST_PERMISSIONS", [
    "fileId",
    "pageSize",
    "pageToken",
    "supportsAllDrives",
    "useDomainAdminAccess",
    "includePermissionsForView",
  ]),
  composioAction("GOOGLEDRIVE_LIST_REPLIES", [
    "fields",
    "file_id",
    "page_size",
    "comment_id",
    "page_token",
    "include_deleted",
  ]),
  composioAction("GOOGLEDRIVE_LIST_REVISIONS", [
    "fileId",
    "pageSize",
    "pageToken",
    "supportsAllDrives",
  ]),
  composioAction("GOOGLEDRIVE_LIST_SHARED_DRIVES", [
    "q",
    "pageSize",
    "pageToken",
    "useDomainAdminAccess",
  ]),
  composioAction("GOOGLEDRIVE_LIST_TEAM_DRIVES", [
    "q",
    "alt",
    "key",
    "xgafv",
    "fields",
    "callback",
    "pageSize",
    "pageToken",
    "quotaUser",
    "uploadType",
  ]),
  composioAction("GOOGLEDRIVE_MODIFY_FILE_LABELS", [
    "kind",
    "file_id",
    "label_modifications",
  ]),
  composioAction("GOOGLEDRIVE_MOVE_FILE", [
    "file_id",
    "add_parents",
    "ocr_language",
    "include_labels",
    "remove_parents",
    "supports_all_drives",
    "keep_revision_forever",
    "include_permissions_for_view",
    "use_content_as_indexable_text",
  ]),
  composioAction("GOOGLEDRIVE_PARSE_FILE", ["file_id", "mime_type"]),
  composioAction("GOOGLEDRIVE_PATCH_PERMISSION", [
    "role",
    "file_id",
    "with_link",
    "permission_id",
    "expiration_date",
    "additional_roles",
    "remove_expiration",
    "transfer_ownership",
    "supports_all_drives",
    "use_domain_admin_access",
  ]),
  composioAction("GOOGLEDRIVE_PATCH_PROPERTY", [
    "alt",
    "key",
    "value",
    "xgafv",
    "fields",
    "fileId",
    "callback",
    "quotaUser",
    "uploadType",
    "visibility",
  ]),
  composioAction("GOOGLEDRIVE_RESUMABLE_UPLOAD", [
    "file_id",
    "metadata",
    "chunkSize",
    "queryParams",
    "file_to_upload",
    "folder_to_upload_to",
  ]),
  composioAction("GOOGLEDRIVE_STOP_WATCH_CHANNEL", [
    "id",
    "kind",
    "token",
    "params",
    "address",
    "payload",
    "expiration",
    "resourceId",
    "channelType",
    "resourceUri",
  ]),
  composioAction("GOOGLEDRIVE_TRASH_FILE", [
    "fields",
    "file_id",
    "supportsAllDrives",
  ]),
  composioAction("GOOGLEDRIVE_UNHIDE_DRIVE", ["driveId"]),
  composioAction("GOOGLEDRIVE_UNTRASH_FILE", ["file_id", "supportsAllDrives"]),
  composioAction("GOOGLEDRIVE_UPDATE_COMMENT", [
    "fields",
    "content",
    "file_id",
    "resolved",
    "comment_id",
  ]),
  composioAction("GOOGLEDRIVE_UPDATE_DRIVE", [
    "name",
    "hidden",
    "driveId",
    "themeId",
    "colorRgb",
    "restrictions",
    "backgroundImageFile",
    "useDomainAdminAccess",
  ]),
  composioAction("GOOGLEDRIVE_UPDATE_FILE_METADATA_PATCH", [
    "ocr",
    "title",
    "fileId",
    "labels",
    "pinned",
    "mimeType",
    "addParents",
    "properties",
    "description",
    "newRevision",
  ]),
  composioAction("GOOGLEDRIVE_UPDATE_FILE_PROPERTY", [
    "alt",
    "key",
    "xgafv",
    "fields",
    "fileId",
    "callback",
    "quotaUser",
    "uploadType",
    "visibility",
    "oauth_token",
  ]),
  composioAction("GOOGLEDRIVE_UPDATE_FILE_PUT", [
    "name",
    "fileId",
    "starred",
    "mime_type",
    "add_parents",
    "description",
    "ocr_language",
    "remove_parents",
    "writers_can_share",
    "supports_all_drives",
  ]),
  composioAction("GOOGLEDRIVE_UPDATE_FILE_REVISION_METADATA", [
    "file_id",
    "published",
    "keepForever",
    "publishAuto",
    "revision_id",
    "publishedOutsideDomain",
  ]),
  composioAction("GOOGLEDRIVE_UPDATE_PERMISSION", [
    "fileId",
    "permission",
    "permissionId",
    "removeExpiration",
    "supportsAllDrives",
    "transferOwnership",
    "useDomainAdminAccess",
    "enforceExpansiveAccess",
  ]),
  composioAction("GOOGLEDRIVE_UPDATE_REPLY", [
    "fields",
    "content",
    "file_id",
    "reply_id",
    "comment_id",
  ]),
  composioAction("GOOGLEDRIVE_UPDATE_TEAM_DRIVE", [
    "name",
    "themeId",
    "colorRgb",
    "teamDriveId",
    "restrictions",
    "backgroundImageFile",
    "useDomainAdminAccess",
  ]),
  composioAction("GOOGLEDRIVE_UPLOAD_FILE", [
    "file_to_upload",
    "folder_to_upload_to",
  ]),
  composioAction("GOOGLEDRIVE_UPLOAD_FROM_URL", [
    "name",
    "mime_type",
    "source_url",
    "verify_ssl",
    "source_headers",
    "parent_folder_id",
    "supports_all_drives",
  ]),
  composioAction("GOOGLEDRIVE_UPLOAD_UPDATE_FILE", [
    "fileId",
    "addParents",
    "uploadType",
    "ocrLanguage",
    "removeParents",
    "file_to_upload",
    "supportsAllDrives",
    "keepRevisionForever",
    "useContentAsIndexableText",
  ]),
  composioAction("GOOGLEDRIVE_WATCH_CHANGES", [
    "id",
    "type",
    "token",
    "params",
    "spaces",
    "address",
    "drive_id",
    "page_size",
    "expiration",
    "page_token",
  ]),
  composioAction("GOOGLEDRIVE_WATCH_FILE", [
    "id",
    "type",
    "token",
    "fileId",
    "params",
    "address",
    "payload",
    "expiration",
    "includeLabels",
    "acknowledgeAbuse",
  ]),
]

export const GOOGLE_SHEETS_TRIGGERS: IntegrationTrigger[] = [
  composioTrigger(
    "GOOGLESHEETS_AGGREGATE_METRIC_CHANGED_TRIGGER",
    "Aggregate Metric Changed",
    [
      "case_sensitive",
      "has_header_row",
      "interval",
      "operation",
      "percentage_total",
      "search_column",
      "search_value",
      "sheet_name",
      "spreadsheet_id",
      "target_column",
    ]
  ),
  composioTrigger(
    "GOOGLESHEETS_CELL_RANGE_VALUES_CHANGED_TRIGGER",
    "Cell Range Values Changed",
    ["interval", "range", "spreadsheet_id"]
  ),
  composioTrigger(
    "GOOGLESHEETS_CONDITIONAL_FORMAT_RULE_CHANGED_TRIGGER",
    "Conditional Format Rule Changed",
    ["interval", "sheet_id", "sheet_title", "spreadsheet_id"]
  ),
  composioTrigger(
    "GOOGLESHEETS_DATA_VALIDATION_RULE_CHANGED_TRIGGER",
    "Data Validation Rule Changed",
    ["interval", "ranges", "sheet_id", "sheet_title", "spreadsheet_id"]
  ),
  composioTrigger(
    "GOOGLESHEETS_DEVELOPER_METADATA_CHANGED_TRIGGER",
    "Developer Metadata Changed",
    ["data_filters", "interval", "spreadsheet_id"]
  ),
  composioTrigger(
    "GOOGLESHEETS_FILTERED_RANGE_VALUES_CHANGED_TRIGGER",
    "Filtered Range Values Changed",
    [
      "data_filters",
      "interval",
      "major_dimension",
      "spreadsheet_id",
      "value_render_option",
    ]
  ),
  composioTrigger("GOOGLESHEETS_NEW_ROWS_TRIGGER", "New Rows in Google Sheet", [
    "interval",
    "sheet_name",
    "spreadsheet_id",
    "start_row",
  ]),
  composioTrigger(
    "GOOGLESHEETS_NEW_SHEET_ADDED_TRIGGER",
    "New Sheet Added in Google Spreadsheet",
    ["interval", "spreadsheet_id"]
  ),
  composioTrigger(
    "GOOGLESHEETS_NEW_SPREADSHEET_CREATED_TRIGGER",
    "New Spreadsheet Created",
    ["include_shared_drives", "interval", "max_results", "query"]
  ),
  composioTrigger(
    "GOOGLESHEETS_SPREADSHEET_METADATA_CHANGED_TRIGGER",
    "Spreadsheet Metadata Changed",
    ["interval", "spreadsheet_id"]
  ),
  composioTrigger(
    "GOOGLESHEETS_SPREADSHEET_PROPERTIES_CHANGED_TRIGGER",
    "Spreadsheet Properties Changed",
    ["interval", "spreadsheet_id"]
  ),
  composioTrigger(
    "GOOGLESHEETS_SPREADSHEET_ROW_CHANGED_TRIGGER",
    "Spreadsheet Row Changed",
    [
      "case_sensitive",
      "interval",
      "normalize_whitespace",
      "query",
      "range",
      "spreadsheet_id",
    ]
  ),
  composioTrigger(
    "GOOGLESHEETS_SPREADSHEET_SEARCH_MATCH_TRIGGER",
    "Spreadsheet Search Match",
    [
      "created_after",
      "include_shared_drives",
      "include_trashed",
      "interval",
      "max_results",
      "modified_after",
      "order_by",
      "query",
      "search_type",
      "shared_with_me",
      "starred_only",
    ]
  ),
  composioTrigger(
    "GOOGLESHEETS_TABLE_QUERY_RESULT_CHANGED_TRIGGER",
    "Table Query Result Changed",
    ["include_formulas", "interval", "spreadsheet_id", "sql"]
  ),
  composioTrigger(
    "GOOGLESHEETS_TABLE_SCHEMA_CHANGED_TRIGGER",
    "Table Schema Changed",
    ["interval", "sample_size", "sheet_name", "spreadsheet_id", "table_name"]
  ),
  composioTrigger(
    "GOOGLESHEETS_WORKSHEET_NAMES_CHANGED_TRIGGER",
    "Worksheet Names Changed",
    ["interval", "spreadsheet_id"]
  ),
]

export const GOOGLE_SHEETS_ACTIONS: IntegrationAction[] = [
  composioAction("GOOGLESHEETS_ADD_SHEET", [
    "title",
    "properties",
    "force_unique",
    "spreadsheet_id",
    "data_source_config",
    "object_sheet_config",
  ]),
  composioAction("GOOGLESHEETS_AGGREGATE_COLUMN_DATA", [
    "operation",
    "sheet_name",
    "search_value",
    "search_column",
    "target_column",
    "case_sensitive",
    "has_header_row",
    "spreadsheet_id",
    "percentage_total",
    "additional_filters",
  ]),
  composioAction("GOOGLESHEETS_APPEND_DIMENSION", [
    "length",
    "sheet_id",
    "dimension",
    "spreadsheet_id",
    "response_ranges",
    "response_include_grid_data",
    "include_spreadsheet_in_response",
  ]),
  composioAction("GOOGLESHEETS_AUTO_RESIZE_DIMENSIONS", [
    "sheet_id",
    "dimension",
    "end_index",
    "sheet_name",
    "start_index",
    "spreadsheet_id",
  ]),
  composioAction("GOOGLESHEETS_BATCH_CLEAR_VALUES_BY_DATA_FILTER", [
    "dataFilters",
    "spreadsheetId",
  ]),
  composioAction("GOOGLESHEETS_BATCH_GET", [
    "ranges",
    "majorDimension",
    "spreadsheet_id",
    "valueRenderOption",
    "dateTimeRenderOption",
    "empty_strings_filtered",
  ]),
  composioAction("GOOGLESHEETS_BATCH_UPDATE", [
    "values",
    "sheet_name",
    "spreadsheet_id",
    "value_input_option",
    "first_cell_location",
    "include_values_in_response",
  ]),
  composioAction("GOOGLESHEETS_BATCH_UPDATE_VALUES_BY_DATA_FILTER", [
    "data",
    "spreadsheetId",
    "valueInputOption",
    "includeValuesInResponse",
    "responseValueRenderOption",
    "responseDateTimeRenderOption",
  ]),
  composioAction("GOOGLESHEETS_CLEAR_BASIC_FILTER", [
    "sheet_id",
    "spreadsheet_id",
    "response_ranges",
    "response_include_grid_data",
    "include_spreadsheet_in_response",
  ]),
  composioAction("GOOGLESHEETS_CLEAR_VALUES", ["range", "spreadsheet_id"]),
  composioAction("GOOGLESHEETS_CREATE_CHART", [
    "title",
    "sheet_id",
    "subtitle",
    "chart_spec",
    "chart_type",
    "data_range",
    "x_axis_title",
    "y_axis_title",
    "background_red",
    "spreadsheet_id",
  ]),
  composioAction("GOOGLESHEETS_CREATE_GOOGLE_SHEET1", [
    "title",
    "folder_id",
    "folder_name",
  ]),
  composioAction("GOOGLESHEETS_CREATE_SPREADSHEET_COLUMN", [
    "sheet_id",
    "sheet_name",
    "insert_index",
    "spreadsheet_id",
    "response_ranges",
    "inherit_from_before",
    "response_include_grid_data",
    "include_spreadsheet_in_response",
  ]),
  composioAction("GOOGLESHEETS_CREATE_SPREADSHEET_ROW", [
    "sheet_id",
    "sheet_name",
    "insert_index",
    "spreadsheet_id",
    "response_ranges",
    "inherit_from_before",
    "response_include_grid_data",
    "include_spreadsheet_in_response",
  ]),
  composioAction("GOOGLESHEETS_DELETE_CHART", ["chart_id", "spreadsheet_id"]),
  composioAction("GOOGLESHEETS_DELETE_DIMENSION", [
    "sheet_id",
    "dimension",
    "end_index",
    "sheet_name",
    "start_index",
    "spreadsheet_id",
    "response_ranges",
    "delete_dimension_request",
    "response_include_grid_data",
    "include_spreadsheet_in_response",
  ]),
  composioAction("GOOGLESHEETS_DELETE_SHEET", [
    "sheetId",
    "spreadsheetId",
    "responseRanges",
    "responseIncludeGridData",
    "includeSpreadsheetInResponse",
  ]),
  composioAction("GOOGLESHEETS_EXECUTE_SQL", [
    "sql",
    "dry_run",
    "delete_method",
    "spreadsheet_id",
  ]),
  composioAction("GOOGLESHEETS_FIND_REPLACE", [
    "find",
    "range",
    "replace",
    "sheetId",
    "allSheets",
    "matchCase",
    "sheetName",
    "endRowIndex",
    "rangeSheetId",
    "searchByRegex",
  ]),
  composioAction("GOOGLESHEETS_FIND_WORKSHEET_BY_TITLE", [
    "spreadsheet_id",
    "worksheet_title",
  ]),
  composioAction("GOOGLESHEETS_FORMAT_CELL", [
    "red",
    "blue",
    "bold",
    "green",
    "range",
    "italic",
    "font_size",
    "text_link",
    "underline",
    "sheet_name",
  ]),
  composioAction("GOOGLESHEETS_GET_BATCH_VALUES", [
    "ranges",
    "spreadsheet_id",
    "major_dimension",
    "value_render_option",
    "date_time_render_option",
  ]),
  composioAction("GOOGLESHEETS_GET_CONDITIONAL_FORMAT_RULES", [
    "sheet_id",
    "sheet_title",
    "spreadsheet_id",
    "exclude_tables_in_banded_ranges",
  ]),
  composioAction("GOOGLESHEETS_GET_DATA_VALIDATION_RULES", [
    "ranges",
    "sheetId",
    "sheetTitle",
    "includeEmpty",
    "spreadsheetId",
  ]),
  composioAction("GOOGLESHEETS_GET_SHEET_NAMES", [
    "exclude_hidden",
    "spreadsheet_id",
  ]),
  composioAction("GOOGLESHEETS_GET_SPREADSHEET_BY_DATA_FILTER", [
    "dataFilters",
    "spreadsheetId",
    "includeGridData",
    "excludeTablesInBandedRanges",
  ]),
  composioAction("GOOGLESHEETS_GET_SPREADSHEET_INFO", [
    "fields",
    "ranges",
    "spreadsheet_id",
    "include_grid_data",
    "exclude_tables_in_banded_ranges",
  ]),
  composioAction("GOOGLESHEETS_GET_TABLE_SCHEMA", [
    "sheet_name",
    "table_name",
    "sample_size",
    "spreadsheet_id",
  ]),
  composioAction("GOOGLESHEETS_INSERT_DIMENSION", [
    "spreadsheet_id",
    "response_ranges",
    "insert_dimension",
    "response_include_grid_data",
    "include_spreadsheet_in_response",
  ]),
  composioAction("GOOGLESHEETS_LIST_CHARTS", [
    "chart_id",
    "sheet_id",
    "include_spec",
    "spreadsheet_id",
  ]),
  composioAction("GOOGLESHEETS_LIST_TABLES", [
    "min_rows",
    "min_columns",
    "min_confidence",
    "spreadsheet_id",
  ]),
  composioAction("GOOGLESHEETS_LOOKUP_SPREADSHEET_ROW", [
    "query",
    "range",
    "case_sensitive",
    "spreadsheet_id",
    "value_render_option",
    "normalize_whitespace",
    "date_time_render_option",
  ]),
  composioAction("GOOGLESHEETS_MOVE_CHART", [
    "chart_id",
    "new_sheet",
    "width_pixels",
    "height_pixels",
    "spreadsheet_id",
    "anchor_sheet_id",
    "offset_x_pixels",
    "offset_y_pixels",
    "target_sheet_id",
    "anchor_row_index",
  ]),
  composioAction("GOOGLESHEETS_MUTATE_CONDITIONAL_FORMAT_RULES", [
    "rule",
    "index",
    "sheet_id",
    "new_index",
    "operation",
    "spreadsheet_id",
  ]),
  composioAction("GOOGLESHEETS_QUERY_TABLE", [
    "sql",
    "spreadsheet_id",
    "include_formulas",
  ]),
  composioAction("GOOGLESHEETS_SEARCH_DEVELOPER_METADATA", [
    "dataFilters",
    "spreadsheetId",
  ]),
  composioAction("GOOGLESHEETS_SEARCH_SPREADSHEETS", [
    "query",
    "order_by",
    "page_token",
    "max_results",
    "search_type",
    "starred_only",
    "created_after",
    "modified_after",
    "shared_with_me",
    "include_trashed",
  ]),
  composioAction("GOOGLESHEETS_SET_BASIC_FILTER", [
    "filter",
    "spreadsheetId",
    "responseRanges",
    "responseIncludeGridData",
    "includeSpreadsheetInResponse",
  ]),
  composioAction("GOOGLESHEETS_SET_DATA_VALIDATION_RULE", [
    "mode",
    "strict",
    "values",
    "formula",
    "sheet_id",
    "end_row_index",
    "input_message",
    "show_custom_ui",
    "spreadsheet_id",
    "source_range_a1",
  ]),
  composioAction("GOOGLESHEETS_SHEET_FROM_JSON", [
    "title",
    "sheet_json",
    "sheet_name",
  ]),
  composioAction("GOOGLESHEETS_SORT_RANGE", [
    "range",
    "sortSpecs",
    "responseRanges",
    "spreadsheet_id",
    "responseIncludeGridData",
    "includeSpreadsheetInResponse",
  ]),
  composioAction("GOOGLESHEETS_SPREADSHEETS_SHEETS_COPY_TO", [
    "sheet_id",
    "spreadsheet_id",
    "destination_spreadsheet_id",
  ]),
  composioAction("GOOGLESHEETS_SPREADSHEETS_VALUES_APPEND", [
    "range",
    "values",
    "spreadsheetId",
    "majorDimension",
    "insertDataOption",
    "valueInputOption",
    "includeValuesInResponse",
    "responseValueRenderOption",
    "responseDateTimeRenderOption",
  ]),
  composioAction("GOOGLESHEETS_SPREADSHEETS_VALUES_BATCH_CLEAR", [
    "ranges",
    "spreadsheet_id",
  ]),
  composioAction("GOOGLESHEETS_SPREADSHEETS_VALUES_BATCH_GET_BY_DATA_FILTER", [
    "dataFilters",
    "spreadsheetId",
    "majorDimension",
    "valueRenderOption",
    "dateTimeRenderOption",
  ]),
  composioAction("GOOGLESHEETS_UPDATE_CHART", [
    "chart_id",
    "chart_spec",
    "spreadsheet_id",
  ]),
  composioAction("GOOGLESHEETS_UPDATE_DIMENSION_PROPERTIES", [
    "sheet_id",
    "dimension",
    "end_index",
    "pixel_size",
    "sheet_name",
    "start_index",
    "hidden_by_user",
    "spreadsheet_id",
    "response_ranges",
    "response_include_grid_data",
  ]),
  composioAction("GOOGLESHEETS_UPDATE_SHEET_PROPERTIES", [
    "spreadsheetId",
    "responseRanges",
    "updateSheetProperties",
    "responseIncludeGridData",
    "includeSpreadsheetInResponse",
  ]),
  composioAction("GOOGLESHEETS_UPDATE_SPREADSHEET_PROPERTIES", [
    "fields",
    "properties",
    "spreadsheetId",
    "responseRanges",
    "responseIncludeGridData",
    "includeSpreadsheetInResponse",
  ]),
  composioAction("GOOGLESHEETS_UPDATE_VALUES_BATCH", [
    "data",
    "spreadsheet_id",
    "valueInputOption",
    "includeValuesInResponse",
    "responseValueRenderOption",
    "responseDateTimeRenderOption",
  ]),
  composioAction("GOOGLESHEETS_UPSERT_ROWS", [
    "rows",
    "headers",
    "keyColumn",
    "sheetName",
    "strictMode",
    "tableStart",
    "spreadsheetId",
    "key_column_index",
    "normalization_message",
  ]),
  composioAction("GOOGLESHEETS_VALUES_GET", [
    "range",
    "end_row",
    "start_row",
    "spreadsheet_id",
    "major_dimension",
    "value_render_option",
    "date_time_render_option",
  ]),
  composioAction("GOOGLESHEETS_VALUES_UPDATE", [
    "range",
    "values",
    "spreadsheet_id",
    "major_dimension",
    "auto_expand_sheet",
    "value_input_option",
    "include_values_in_response",
    "response_value_render_option",
    "response_datetime_render_option",
  ]),
]

export const GOOGLE_DOCS_TRIGGERS: IntegrationTrigger[] = [
  composioTrigger(
    "GOOGLEDOCS_DOCUMENT_CREATED_TRIGGER",
    "New Document Created",
    ["interval", "max_results", "query"]
  ),
  composioTrigger("GOOGLEDOCS_DOCUMENT_DELETED_TRIGGER", "Document Deleted", [
    "interval",
    "max_results",
    "query",
  ]),
  composioTrigger(
    "GOOGLEDOCS_DOCUMENT_PLACEHOLDER_FILLED_TRIGGER",
    "Document Placeholder Filled",
    [
      "case_sensitive",
      "document_id",
      "include_footers",
      "include_footnotes",
      "include_headers",
      "interval",
      "placeholder_pattern",
      "use_regex",
    ]
  ),
  composioTrigger(
    "GOOGLEDOCS_DOCUMENT_SEARCH_UPDATE_TRIGGER",
    "Document Search Update",
    [
      "include_shared_drives",
      "include_trashed",
      "interval",
      "max_results",
      "query",
      "shared_with_me",
      "starred_only",
    ]
  ),
  composioTrigger(
    "GOOGLEDOCS_DOCUMENT_STRUCTURE_CHANGED_TRIGGER",
    "Document Structure Changed",
    ["document_id", "interval"]
  ),
  composioTrigger("GOOGLEDOCS_DOCUMENT_UPDATED_TRIGGER", "Document Updated", [
    "interval",
    "max_results",
    "query",
  ]),
  composioTrigger(
    "GOOGLEDOCS_DOCUMENT_WORD_COUNT_THRESHOLD_TRIGGER",
    "Document Word Count Threshold",
    ["document_id", "interval", "use_character_count", "word_count_threshold"]
  ),
  composioTrigger(
    "GOOGLEDOCS_FOLDER_CREATED_TRIGGER",
    "New Folder Created in Root",
    ["interval", "max_results"]
  ),
  composioTrigger(
    "GOOGLEDOCS_KEYWORD_DETECTED_TRIGGER",
    "Keyword Detected in Document",
    [
      "case_sensitive",
      "document_id",
      "include_footers",
      "include_footnotes",
      "include_headers",
      "interval",
      "keyword",
    ]
  ),
  composioTrigger("GOOGLEDOCS_PAGE_ADDED_TRIGGER", "New Document Added", [
    "interval",
    "max_results",
    "query",
  ]),
]

export const GOOGLE_DOCS_ACTIONS: IntegrationAction[] = [
  composioAction("GOOGLEDOCS_COPY_DOCUMENT", [
    "title",
    "document_id",
    "include_shared_drives",
  ]),
  composioAction("GOOGLEDOCS_CREATE_AND_POPULATE_TABLE", [
    "rows",
    "index",
    "tabId",
    "columns",
    "cellData",
    "segmentId",
    "documentId",
    "insertAtEndOfSegment",
  ]),
  composioAction("GOOGLEDOCS_CREATE_DOCUMENT", ["text", "title"]),
  composioAction("GOOGLEDOCS_CREATE_DOCUMENT2", ["title"]),
  composioAction("GOOGLEDOCS_CREATE_DOCUMENT_MARKDOWN", [
    "title",
    "image_assets",
    "markdown_text",
  ]),
  composioAction("GOOGLEDOCS_CREATE_FOOTER", [
    "type",
    "document_id",
    "section_break_location",
  ]),
  composioAction("GOOGLEDOCS_CREATE_FOOTNOTE", [
    "location",
    "documentId",
    "endOfSegmentLocation",
  ]),
  composioAction("GOOGLEDOCS_CREATE_HEADER", [
    "text",
    "type",
    "documentId",
    "sectionBreakLocation",
  ]),
  composioAction("GOOGLEDOCS_CREATE_NAMED_RANGE", [
    "name",
    "tabId",
    "documentId",
    "rangeEndIndex",
    "rangeSegmentId",
    "rangeStartIndex",
  ]),
  composioAction("GOOGLEDOCS_CREATE_PARAGRAPH_BULLETS", [
    "tabId",
    "document_id",
    "createParagraphBullets",
  ]),
  composioAction("GOOGLEDOCS_CREATE_TAB", ["document_id", "tab_properties"]),
  composioAction("GOOGLEDOCS_DELETE_CONTENT_RANGE", ["range", "document_id"]),
  composioAction("GOOGLEDOCS_DELETE_FOOTER", [
    "tab_id",
    "footer_id",
    "document_id",
  ]),
  composioAction("GOOGLEDOCS_DELETE_HEADER", [
    "tab_id",
    "header_id",
    "document_id",
  ]),
  composioAction("GOOGLEDOCS_DELETE_NAMED_RANGE", [
    "document_id",
    "deleteNamedRange",
  ]),
  composioAction("GOOGLEDOCS_DELETE_PARAGRAPH_BULLETS", [
    "range",
    "tab_id",
    "document_id",
  ]),
  composioAction("GOOGLEDOCS_DELETE_TAB", ["tab_id", "document_id"]),
  composioAction("GOOGLEDOCS_DELETE_TABLE_COLUMN", ["requests", "document_id"]),
  composioAction("GOOGLEDOCS_DELETE_TABLE_ROW", [
    "documentId",
    "tableCellLocation",
  ]),
  composioAction("GOOGLEDOCS_EXPORT_DOCUMENT_AS_PDF", ["file_id", "filename"]),
  composioAction("GOOGLEDOCS_GET_DOCUMENT_BY_ID", ["id", "includeTabsContent"]),
  composioAction("GOOGLEDOCS_GET_DOCUMENT_END_INDEX", [
    "tab_id",
    "segment_id",
    "document_id",
  ]),
  composioAction("GOOGLEDOCS_GET_DOCUMENT_PLAINTEXT", [
    "tab_ids",
    "document_id",
    "include_tables",
    "include_footers",
    "include_headers",
    "include_footnotes",
    "table_row_delimiter",
    "include_tabs_content",
    "table_cell_delimiter",
  ]),
  composioAction("GOOGLEDOCS_INSERT_IMAGE_IN_TABLE_CELL", [
    "uri",
    "document_id",
    "object_size",
    "cell_content_index",
    "table_cell_location",
  ]),
  composioAction("GOOGLEDOCS_INSERT_INLINE_IMAGE", [
    "uri",
    "location",
    "documentId",
    "objectSize",
  ]),
  composioAction("GOOGLEDOCS_INSERT_PAGE_BREAK", [
    "documentId",
    "insertPageBreak",
  ]),
  composioAction("GOOGLEDOCS_INSERT_TABLE_ACTION", [
    "rows",
    "index",
    "tabId",
    "columns",
    "segmentId",
    "documentId",
    "insertAtEndOfSegment",
  ]),
  composioAction("GOOGLEDOCS_INSERT_TABLE_COLUMN", ["requests", "document_id"]),
  composioAction("GOOGLEDOCS_INSERT_TABLE_ROW", ["requests", "document_id"]),
  composioAction("GOOGLEDOCS_INSERT_TEXT_ACTION", [
    "tab_id",
    "segment_id",
    "document_id",
    "append_to_end",
    "text_to_insert",
    "insertion_index",
  ]),
  composioAction("GOOGLEDOCS_INSERT_TEXT_IN_TABLE_CELL", [
    "text",
    "tabId",
    "row_index",
    "document_id",
    "column_index",
    "table_start_index",
  ]),
  composioAction("GOOGLEDOCS_LIST_SPREADSHEET_CHARTS", ["spreadsheet_id"]),
  composioAction("GOOGLEDOCS_REPLACE_ALL_TEXT", [
    "tab_ids",
    "find_text",
    "match_case",
    "document_id",
    "replace_text",
    "search_by_regex",
  ]),
  composioAction("GOOGLEDOCS_REPLACE_IMAGE", ["document_id", "replace_image"]),
  composioAction("GOOGLEDOCS_SEARCH_DOCUMENTS", [
    "query",
    "order_by",
    "page_token",
    "max_results",
    "starred_only",
    "created_after",
    "modified_after",
    "shared_with_me",
    "include_trashed",
    "response_detail",
  ]),
  composioAction("GOOGLEDOCS_UNMERGE_TABLE_CELLS", [
    "documentId",
    "tableRange",
  ]),
  composioAction("GOOGLEDOCS_UPDATE_DOCUMENT_BATCH", [
    "requests",
    "document_id",
    "write_control",
  ]),
  composioAction("GOOGLEDOCS_UPDATE_DOCUMENT_MARKDOWN", [
    "id",
    "tab_id",
    "markdown",
  ]),
  composioAction("GOOGLEDOCS_UPDATE_DOCUMENT_SECTION_MARKDOWN", [
    "tab_id",
    "end_index",
    "document_id",
    "start_index",
    "markdown_text",
  ]),
  composioAction("GOOGLEDOCS_UPDATE_DOCUMENT_STYLE", [
    "fields",
    "tab_id",
    "document_id",
    "document_style",
  ]),
  composioAction("GOOGLEDOCS_UPDATE_EXISTING_DOCUMENT", [
    "edit_docs",
    "document_id",
  ]),
  composioAction("GOOGLEDOCS_UPDATE_TABLE_ROW_STYLE", [
    "documentId",
    "updateTableRowStyle",
  ]),
  composioAction("GOOGLEDOCS_UPDATE_TAB_PROPERTIES", [
    "fields",
    "tab_id",
    "document_id",
    "tab_properties",
  ]),
]
